modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/nuclearmekanism/NuclearEntangloporter/issues"

[[mods]]
modId="nuclearentangloporter"
version="${file.jarVersion}"
displayName="Nuclear Entangloporter"
authors="Nuclear Mekanism Team"
description='''A Mekanism add-on that mirrors the Quantum Entangloporter while also transporting radioactive chemicals.'''
displayURL="https://github.com/nuclearmekanism/NuclearEntangloporter"

[[mixins]]
config="nuclearentangloporter.mixins.json"

[[dependencies.nuclearentangloporter]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.nuclearentangloporter]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.nuclearentangloporter]]
modId="mekanism"
type="required"
versionRange="[10.7.19,)"
ordering="NONE"
side="BOTH"

[[dependencies.nuclearentangloporter]]
modId="ae2"
type="optional"
versionRange="[19.2.17,)"
ordering="AFTER"
side="BOTH"

[[dependencies.nuclearentangloporter]]
modId="refinedstorage"
type="optional"
versionRange="[2.0.9,)"
ordering="AFTER"
side="BOTH"
